apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-demo1
  annotations:
    DOSLAB_IO_GPU_ASSUME_TIME: "1629424836302184400"
    DOSLAB_IO_GPU_ASSIGNED: "false"
    DOSLAB_IO_GPU_UUID: "GPU-21f591ed-d77b-3a27-c674-51375d2e4fd9"
spec:
  restartPolicy: Never
  containers:
    - image: nvidia/cuda:10.1-base-ubuntu18.04
      name: gpu-pod-demo1
      command: ["sleep"]
      args: ["100000"]
      resources:
        limits:
          doslab.io/gpu-memory: 1024  # 1024MB'
  nodeSelector:
    kubernetes.io/hostname: dell04