---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-demo1
  annotations:
    DOSLAB_IO_GPU_ASSUME_TIME: "1629424836302184400"
    DOSLAB_IO_GPU_ASSIGNED: "false"
    DOSLAB_IO_GPU_UUID: "GPU-21f591ed-d77b-3a27-c674-51375d2e4fd9"
spec:
  restartPolicy: Never
  containers:
    - image: nvidia/cuda:10.1-base-ubuntu18.04
      name: gpu-pod-demo1
      command: ["sleep"]
      args: ["1000000"]
      resources:
        limits:
          doslab.io/gpu-memory: 1024  # 1024MB
          doslab.io/gpu-core: 15
  nodeSelector:
    kubernetes.io/hostname: dell04
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-demo2
  annotations:
    DOSLAB_IO_GPU_ASSUME_TIME: "1629424836302184999"
    DOSLAB_IO_GPU_ASSIGNED: "false"
    DOSLAB_IO_GPU_UUID: "GPU-21f591ed-d77b-3a27-c674-51375d2e4fd9"
spec:
  restartPolicy: Never
  containers:
    - image: nvidia/cuda:10.1-base-ubuntu18.04
      name: gpu-pod-demo2
      command: ["sleep"]
      args: ["1000000"]
      resources:
        limits:
          doslab.io/gpu-memory: 1024  # 1024MB
          doslab.io/gpu-core: 12
  nodeSelector:
    kubernetes.io/hostname: dell04
---
apiVersion: v1
kind: Pod
metadata:
  name: po-1
spec:
  schedulerName: doslab-gpu-scheduler
  containers:
    - image: nvidia/cuda:10.1-base-ubuntu18.04
      name: gpu-pod-demo2
      command: ["sleep"]
      args: ["1000000"]
      resources:
        limits:
          doslab.io/gpu-memory: 2048  # 1024MB
          doslab.io/gpu-core: 20
